CREATE TABLE assessment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID UNIQUE                             NOT NULL,
    created_at TIMESTAMPTZ                             NOT NULL,
    CONSTRAINT pk_assessment PRIMARY KEY (id)
);

CREATE INDEX ix_assessment_uuid ON assessment (uuid);

CREATE TABLE event
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY           NOT NULL,
    uuid         UUID UNIQUE                                       NOT NULL,
    created_at   TIMESTAMPTZ                                       NOT NULL,
    user_details JSONB                                             NOT NULL,
    data         JSONB                                             NOT NULL,
    data_type    TEXT GENERATED ALWAYS AS (data ->> 'type') STORED NOT NULL,
    assessment_uuid UUID                                              NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_event_assessment FOREIGN KEY (assessment_uuid) REFERENCES assessment (uuid) ON DELETE CASCADE
);

CREATE INDEX ix_event_assessment_uuid ON event (assessment_uuid);

CREATE TABLE aggregate
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY           NOT NULL,
    uuid            UUID UNIQUE                                       NOT NULL,
    updated_at      TIMESTAMPTZ                                       NOT NULL,
    events_from     TIMESTAMPTZ                                       NOT NULL,
    events_to       TIMESTAMPTZ                                       NOT NULL,
    events_applied  BIGINT                                            NOT NULL,
    data            JSONB                                             NOT NULL,
    assessment_uuid UUID                                              NOT NULL,
    CONSTRAINT pk_aggregate PRIMARY KEY (id),
    CONSTRAINT fk_aggregate_assessment FOREIGN KEY (assessment_uuid) REFERENCES assessment (uuid) ON DELETE CASCADE
);

CREATE INDEX ix_aggregate_state_assessment_uuid ON aggregate (assessment_uuid);
